# Generated by Django 4.0.3 on 2022-03-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
